# Generated by Django 3.0.6 on 2021-10-08 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confluence', '0006_meetingminutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingminutes',
            name='meeting_sprint',
            field=models.CharField(default='Not Defined', max_length=256),
        ),
    ]
